version: '3'

services:
    # db:
    #     image: centos/postgresql-96-centos7
    #     command : []
    tactic:
        build: "./tactic"
        environment:
            ROOT_PASSWORD: tactic
        ports:
            - "8070:80"